@HotelListing.Api_HostAddress = https://localhost:7107

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

 {
    "id": 3,
    "name": "Hotel Ana",
    "address": "Calle 25",
    "rating": 3.8
  }

###

@id=1
DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels/1

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/3
Content-Type: application/json

{
    "id": 3,
    "name": "Hotel Santa Ana",
    "address": "Calle 25",
    "rating": 3.8
  }


###



GET {{HotelListing.Api_HostAddress}}/api/countries

###

POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: application/json


{
  "name": "Test Country",
  "shortName": "TC"
}
###
@id=2
DELETE {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###get
@idCountry=3
GET {{HotelListing.Api_HostAddress}}/api/countries/{{idCountry}}

###
@id=3
PUT {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  "id": 3,
  "name": "Mexico",
  "shortName": "MX"
}

###


### hoteles

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

 {
    "Name": "Test Hotel",
    "Address": "Calle 11",
    "rating": 4.8,
    "countryId": 3
 }
###

DELETE {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###
@id=3
GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}

###
@id=2
PUT {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

 {
   "Id": 2,
    "Name": "Hotel America",
    "Address": "Calle 20",
    "rating": 3.5,
    "countryId": 3
 }

###
